version: '3'
services:
  app:
    build:
      context: .
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: hotel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
